spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sys123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 127.0.0.1
    # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 300ms # 连接超时时间（毫秒
    password: sys123
minio:
  endpoint: http://192.168.199.253:9000 #MinIO服务所在地址
  bucketName: img #存储桶名称
  accessKey: admin #访问的key
  secretKey: sys123sys123 #访问的秘钥
  useEndPoint: http://192.168.199.102:8085 #访问地址
system: #以下所有数据不可更改
  admin: zhihaiadmin #开发管理员Username 对应数据库的开发管理员name
  role: 7 #开发管理员所在角色ID
  menu: 24 #菜单列表
  resource: 25 #资源列表

secure:
  ignored:
    urls: #安全路径白名单
      - /home
      - /doc.html
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

