spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sys123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 127.0.0.1
    # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 300ms # 连接超时时间（毫秒
    password: sys123 # redis密码

  data:
    mongodb:
      host: 118.24.13.29
      port: 27017
      database: mall-port
minio:
  endpoint: http://118.24.13.29:9000 #MinIO服务所在地址 本机地址
  bucketName: img #存储桶名称
  accessKey: admin #访问的key
  secretKey: sys123sys123 #访问的秘钥
  useEndPoint: http://118.24.13.29:80 #访问地址 使用反向代理
img:
  savepath: /Users/chengchuanqi/ #系统原上传功能导致图片失真，重写
system: #以下所有数据不可更改
  admin: zhihaiadmin #开发管理员Username 对应数据库的开发管理员name
  role: 7 #开发管理员所在角色ID
  menu: 24 #菜单列表
  resource: 25 #资源列表

# 微信支付配置
# 微信异步通知频率为15/15/30/180/1800/1800/1800/1800/3600，单位：秒
# 公众账号ID
wxpay:
  #测试
  #appId: wx788bdef414e66578
  appId: wxfa70aaa4afffeda1
  # 商户号
  merchantId: 1601714492
  # 商户密钥
  secrectKey: 1234509876bapondtech76bapondtech
  # 支付方式，取值如下：JSAPI，NATIVE，APP
  tradeType: JSAPI
  # 微信支付 - 统一下单地址
  placeOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  # 接收微信支付异步通知回调地址，通知url必须为直接可访问的url，不能携带参数。（需要配置）
  #	public static final String NOTIFY_URL = "http://1s7p978583.iok.la/pay/notice/wxpay.shtml";
  #wxpay.notifyUrl=http://micmcq.natappfree.cc/payment/notice/wxpay
  notifyUrl: http://payment.t.mukewang.com/foodie-payment/payment1/notice/wxpay
  # APP和网页支付提交用户端ip, Native支付填调用微信支付API的机器IP, 即：服务器ip地址
  spbillCreateIp: 192.168.199.101
  #申请退款url
  refoundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund

secure:
  ignored:
    urls: #安全路径白名单
      - /home
      - /doc.html
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
