server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sys123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mall-port

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: sys123 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: admin
    password: admin123
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
# 日志配置
logging:
  path: /var/logs

# 微信小程序配置
#wx:
#  APPID: wxfa70aaa4afffeda1
#  SECRET: 9178aa27624f7a6fd7bc34056dea61e0

#半塘测试
wx:
  APPID: wx788bdef414e66578
  SECRET: fad4ea448d4de3fd97af5be3e4bce76f

minio:
  endpoint: http://47.115.22.3:9000 #MinIO服务所在地址
  bucketName: img #存储桶名称
  accessKey: admin #访问的key
  secretKey: sys123sys123 #访问的秘钥
  localEndPoint: http://47.115.22.3:8081
  useEndPoint: http://47.115.22.3:8081

# 微信支付配置
# 微信异步通知频率为15/15/30/180/1800/1800/1800/1800/3600，单位：秒
# 公众账号ID
wxpay:
  #测试
  appId: wx788bdef414e66578
#  appId: wxfa70aaa4afffeda1
  # 商户号
  merchantId: 1604605057
  # 商户密钥
  secrectKey: 9c2730dfbde8c9a002878d27b83c92a6
  # 支付方式，取值如下：JSAPI，NATIVE，APP
  tradeType: JSAPI
  # 微信支付 - 统一下单地址
  placeOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  # 接收微信支付异步通知回调地址，通知url必须为直接可访问的url，不能携带参数。（需要配置）
  #	public static final String NOTIFY_URL = "http://1s7p978583.iok.la/pay/notice/wxpay.shtml";
  #wxpay.notifyUrl=http://micmcq.natappfree.cc/payment/notice/wxpay
  notifyUrl: https://app-test.geeked.top/portal/payment/notice/wxpay
  # APP和网页支付提交用户端ip, Native支付填调用微信支付API的机器IP, 即：服务器ip地址
  spbillCreateIp: 139.186.153.88
  #申请退款url
  refoundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /point/**
      - /address/**
      - /wx/**
      - /img/**
      - /qr/**
      - /order/**

