server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://192.168.199.253:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sys123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    mongodb:
      host: 192.168.199.253
      port: 27017
      database: mall-port

  redis:
    host: 192.168.199.253
    # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: sys123 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: 192.168.199.253
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug

# 微信小程序配置
wx:
  APPID: wx788bdef414e66578
  SECRET: 5df34df40168609fca84345cdfe0c6fc

minio:
  endpoint: http://192.168.199.253:9000 #MinIO服务所在地址
  bucketName: img #存储桶名称
  accessKey: admin #访问的key
  secretKey: sys123sys123 #访问的秘钥
  localEndPoint: http://192.168.199.253:8085

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /point/**
      - /address/**
      - /wx/**
      - /img/**


